### ISSUE TITLE
Peq redundancy data issue

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#138]
![image003](https://cloud.githubusercontent.com/assets/6067502/6553208/9cbfd6cc-c64e-11e4-9902-c116589df25a.png)

**Comment by borisbergman** [comment]
RZ: Als je de biquads verwijderd hebt, en dan weer de PEQ opent zie je nog steeds 1 BW filter in the curve, maar de lijst is leeg

Should be solved

**Comment by borisbergman** [comment]
- Double BW filters after download
- Shifted frequencies after download

**Comment by RamonZwaga** [comment]
Related to dynamic eprom storage?

**Comment by RamonZwaga** [comment]
Clarity for Michael:
When the EQ is downloaded (after an upload), the result is different. meaning: the displayed frequency curve (based on the redundancy data) is not equal anymore. The data up/downloaded to the DSP seems ok; if you do an analyzer sweep, the outcome is the same as the F-curve which was uploaded. The fault here is probably due to the position in the eprom of the stored info for a double BW filter; once you change this same filter to a single Biquad and it's data is store on the same position (as the double BW), there is still info/data left of the previous filter (as it uses less space for a single Biquad). A few months ago you (michael) told me that the eeprom storage is dynamic, so you cannot assure that the info is put on the correct location. The only way to solve this for Boris is to write the data for each Biquad (single or double) to fixed addresses and make sure that he overwrites all data from a double filter if it has been replaced with a single filter.

**Comment by borisbergman** [comment]
Can't be reproduced by me.

**Comment by RamonZwaga** [comment]
Did you try to add a couple of BW's (4th order) and than change one of them to a Peaking (2nd order)?
Previously a part of the 'old' 4th order BW was still in the memory (so partly overwritten by the 2nd order filter), this causes strange information/curve after download of the EQ. We must be 100% sure that the filter we download (from DSP and from Redundancy data) is exactly the same as the uploaded filter!

This went wrong to often in the past, so we need to make sure that this functions fine for all locations where an EQ can be used (12 outputs, 3x aux, 2x Mic input)!

**Comment by RamonZwaga** [comment]
Tested this with Marius, and sofar all seems to be OK.
Michael to confirm after a final check!
